Add global option
Canner/npm-check-install pull request #8
Opened 2018-10-15 10:12 UTC by chihsuan

https://github.com/Canner/npm-check-install/issues/5

2018-10-16 02:24 UTC, abz53378 requested changes

2018-10-16 02:24 UTC, abz53378 commented on src/installPkg.js
> +  const npmOpt = options.global ? "-g" : "--save";
unused variable

2018-10-16 11:07 UTC, chilijung approved these changes

2018-10-17 05:07 UTC, abz53378 approved these changes

2018-10-17 05:07 UTC, merged